"use client";

import { useCallback, useEffect, useState } from "react";
import { CalendarDays, Loader2, Users, Plus, Check, X, Ban, RefreshCw, Settings2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useI18n } from "@/components/i18n-provider";
import { AccessDenied, SettingsTabs } from "@/components/settings/settings-tabs";
import { usePermissions } from "@/hooks/use-permissions";
import { Skeleton } from "@/components/ui/skeleton";

export default function WorkloadPage() {
  const { t } = useI18n();
  const { has, hasAny } = usePermissions();
  const canViewWorkload = hasAny("planned_leaves.view", "members.view");
  const canManageLeaves = has("planned_leaves.manage");
  const canApproveLeaves = has("planned_leaves.approve");

  const [rows, setRows] = useState<Array<{ profile_id: string; total: number; active: number; overdue: number; capacity_utilization: number | null; over_capacity: boolean; availability: { is_on_leave_now: boolean; next_leave_start: string | null; next_leave_end: string | null }; profile: { display_name: string; email: string | null; max_active_work_items: number } | null }>>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [leaves, setLeaves] = useState<Array<{ id: string; profile_id: string; start_date: string; end_date: string; status: string; reason: string | null; profile?: { display_name: string } }>>([]);
  const [leaveForm, setLeaveForm] = useState({ profile_id: "", start_date: "", end_date: "", reason: "" });
  const [leaveError, setLeaveError] = useState<string | null>(null);
  const [members, setMembers] = useState<Array<{ profile_id: string; name: string; email: string | null }>>([]);
  const [actionState, setActionState] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const loadLeaves = () => fetch("/api/settings/planned-leaves", { cache: "no-store" }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error ?? t("settings.notificationLoadFailed")); setLeaves(body.data ?? []); });
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [workloadResponse] = await Promise.all([fetch("/api/settings/workload"), loadLeaves(), fetch("/api/assignment-members").then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error ?? t("settings.memberLoadFailed")); setMembers(body.data ?? []); })]); const body = await workloadResponse.json(); if (!workloadResponse.ok) throw new Error(body.error ?? t("settings.loadingData")); setRows(body.data ?? []); } catch (err) { setError(err instanceof Error ? err.message : t("settings.loadingData")); } finally { setLoading(false); } }, [t]);
  const submitLeave = async () => { setLeaveError(null); setActionState("create"); setMessage(null); try { const response = await fetch("/api/settings/planned-leaves", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(leaveForm) }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error ?? t("settings.roleCreateFailed")); setLeaveForm({ profile_id: "", start_date: "", end_date: "", reason: "" }); await load(); setMessage(t("settings.requestLeave")); } catch (cause) { setLeaveError(cause instanceof Error ? cause.message : t("settings.roleCreateFailed")); } finally { setActionState(null); } };
  const leaveAction = async (id: string, action: "approve" | "reject") => { const reason = action === "reject" ? window.prompt(t("settings.rejectLeave")) ?? "" : ""; if (action === "reject" && !reason.trim()) return; setActionState(`${action}:${id}`); setMessage(null); try { const response = await fetch(`/api/settings/planned-leaves/${id}?action=${action}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(action === "reject" ? { reason } : {}) }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error ?? t("settings.roleSaveFailed")); await load(); setMessage(action === "approve" ? t("settings.approveLeave") : t("settings.rejectLeave")); } catch (cause) { setLeaveError(cause instanceof Error ? cause.message : t("settings.roleSaveFailed")); } finally { setActionState(null); } };
  const cancelLeave = async (leave: { id: string; status: string }) => { const reason = leave.status === "approved" ? window.prompt(t("settings.cancelLeave")) ?? "" : ""; if (leave.status === "approved" && !reason.trim()) return; setActionState(`cancel:${leave.id}`); setMessage(null); try { const response = await fetch(`/api/settings/planned-leaves/${leave.id}`, { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reason }) }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error ?? t("settings.roleSaveFailed")); await load(); setMessage(t("settings.cancelLeave")); } catch (cause) { setLeaveError(cause instanceof Error ? cause.message : t("settings.roleSaveFailed")); } finally { setActionState(null); } };
  useEffect(() => { queueMicrotask(() => { if (canViewWorkload) void load(); else setLoading(false); }); }, [load, canViewWorkload]);

  if (!canViewWorkload) return <main className="page-canvas text-slate-900"><div className="mx-auto w-full max-w-6xl space-y-6"><SettingsTabs /><AccessDenied /></div></main>;
  if (loading) return <main className="page-canvas"><div className="mx-auto max-w-6xl space-y-5"><Skeleton className="h-12 w-full" /><Skeleton className="h-64 w-full" /><Skeleton className="h-64 w-full" /></div></main>;

  return (
    <main className="page-canvas">
      <div className="mx-auto w-full max-w-6xl space-y-6">
        <SettingsTabs />
        <header><div className="flex items-center gap-2 text-xs font-semibold text-blue-600"><Settings2 className="size-4" /> {t("settings.controlCenter")} <span className="text-slate-400">/</span> {t("settings.general")}</div><h1 className="mt-3 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">{t("settings.workloadTitle")}</h1><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500">{t("settings.workloadDescription")}</p></header>{message && <div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">{message}</div>}
      <section className="surface-card rounded-2xl p-5 sm:p-6">
        <div className="flex items-start justify-between gap-3"><div><Users className="mb-3 size-8 text-blue-600" /><h2 className="text-lg font-bold text-slate-950">{t("settings.workloadDistribution")}</h2><p className="mt-1 text-sm text-slate-500">{t("settings.workloadDistributionDescription")}</p></div><Button variant="outline" size="sm" onClick={() => void load()} disabled={loading}><RefreshCw className="size-4" />{t("settings.refresh")}</Button></div>
        {loading ? <div className="mt-5 flex items-center gap-2 text-sm text-slate-500"><Loader2 className="size-4 animate-spin" />Memuat data...</div> : error ? <div className="mt-5 space-y-2"><p role="alert" className="text-sm text-red-600">{error}</p><button type="button" className="rounded-md border px-3 py-2 text-sm" onClick={() => void load()}>Coba lagi</button></div> : rows.length === 0 ? <p className="mt-3 text-sm text-muted-foreground">Belum ada pekerjaan yang ditugaskan.</p> : <div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs text-muted-foreground"><th className="pb-2">Anggota</th><th className="pb-2">Total</th><th className="pb-2">Aktif</th><th className="pb-2">Kapasitas</th><th className="pb-2">Overdue</th><th className="pb-2">Availability</th></tr></thead><tbody>{rows.map((row) => <tr key={row.profile_id} className="border-b last:border-0"><td className="py-3 font-medium text-ink">{row.profile?.display_name ?? row.profile?.email ?? row.profile_id}</td><td className="py-3">{row.total}</td><td className="py-3">{row.active}</td><td className={row.over_capacity ? "py-3 font-semibold text-red-600" : "py-3"}>{row.capacity_utilization === null ? "—" : `${row.capacity_utilization}%`}</td><td className="py-3 text-red-500">{row.overdue}</td><td className="py-3">{row.availability.is_on_leave_now ? <span className="font-medium text-amber-600">Sedang leave</span> : row.availability.next_leave_start ? <span className="text-slate-500">{row.availability.next_leave_start}–{row.availability.next_leave_end}</span> : <span className="text-emerald-600">Tersedia</span>}</td></tr>)}</tbody></table></div>}
      </section>
      <section className="surface-card mt-6 max-w-4xl rounded-xl p-6">
        <div className="flex items-center justify-between"><div><h2 className="text-base font-semibold text-ink">Planned leave</h2><p className="mt-1 text-sm text-muted-foreground">Ajukan dan proses ketersediaan anggota tim.</p></div><Plus className="size-5 text-blue-600" /></div>
        <div className="mt-4 grid gap-3 md:grid-cols-4"><Select value={leaveForm.profile_id || null} onValueChange={(value) => setLeaveForm({ ...leaveForm, profile_id: value ?? "" })}><SelectTrigger aria-label="Pilih anggota untuk planned leave" className="w-full"><SelectValue placeholder="Pilih anggota" /></SelectTrigger><SelectContent>{members.map((member) => <SelectItem key={member.profile_id} value={member.profile_id}>{member.name}{member.email ? ` · ${member.email}` : ""}</SelectItem>)}</SelectContent></Select><input aria-label="Tanggal mulai leave" className="rounded-md border px-3 py-2 text-sm" type="date" value={leaveForm.start_date} onChange={(event) => setLeaveForm({ ...leaveForm, start_date: event.target.value })} /><input aria-label="Tanggal selesai leave" className="rounded-md border px-3 py-2 text-sm" type="date" value={leaveForm.end_date} onChange={(event) => setLeaveForm({ ...leaveForm, end_date: event.target.value })} /><input aria-label="Alasan planned leave" className="rounded-md border px-3 py-2 text-sm" placeholder="Alasan (opsional)" value={leaveForm.reason} onChange={(event) => setLeaveForm({ ...leaveForm, reason: event.target.value })} /></div>
        <Button type="button" className="cta-primary mt-3" onClick={() => void submitLeave()} disabled={actionState === "create" || !canManageLeaves}>{actionState === "create" && <Loader2 className="size-4 animate-spin" />}Ajukan leave</Button>{leaveError && <p className="mt-2 text-sm text-red-600">{leaveError}</p>}
        <div className="mt-5 overflow-x-auto">{leaves.length === 0 ? <div className="rounded-xl bg-slate-50 p-8 text-center"><CalendarDays className="mx-auto size-8 text-slate-300" /><p className="mt-2 text-sm text-slate-500">Belum ada planned leave.</p></div> : <table className="w-full text-left text-sm"><thead><tr className="border-b text-xs text-slate-500"><th className="pb-3">Profile</th><th className="pb-3">Periode</th><th className="pb-3">Status</th><th className="pb-3">Aksi</th></tr></thead><tbody>{leaves.map((leave) => <tr key={leave.id} className="border-b last:border-0"><td className="py-3 font-medium text-slate-900">{leave.profile?.display_name ?? leave.profile_id}</td><td className="py-3 text-slate-600">{leave.start_date} – {leave.end_date}</td><td className="py-3"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold capitalize text-slate-700">{leave.status}</span></td><td className="py-3"><div className="flex gap-2">{leave.status === "pending" && <><Button variant="ghost" size="icon-sm" disabled={Boolean(actionState) || !canApproveLeaves} aria-label="Setujui planned leave" onClick={() => void leaveAction(leave.id, "approve")}><Check className="size-4 text-emerald-600" /></Button><Button variant="ghost" size="icon-sm" disabled={Boolean(actionState) || !canApproveLeaves} aria-label="Tolak planned leave" onClick={() => void leaveAction(leave.id, "reject")}><X className="size-4 text-red-600" /></Button></>}{["pending", "approved"].includes(leave.status) && <Button variant="ghost" size="icon-sm" disabled={Boolean(actionState) || !canManageLeaves} aria-label="Batalkan planned leave" onClick={() => void cancelLeave(leave)}><Ban className="size-4 text-amber-600" /></Button>}</div></td></tr>)}</tbody></table>}</div>
      </section>
      </div>
    </main>
  );
}
