"use client";

import { useCallback, useEffect, useState } from "react";
import { Loader2, Users, Plus, Check, X, Ban } from "lucide-react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export default function WorkloadPage() {
  const [rows, setRows] = useState<Array<{ profile_id: string; total: number; active: number; overdue: number; capacity_utilization: number | null; over_capacity: boolean; availability: { is_on_leave_now: boolean; next_leave_start: string | null; next_leave_end: string | null }; profile: { display_name: string; email: string | null; max_active_work_items: number } | null }>>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [leaves, setLeaves] = useState<Array<{ id: string; profile_id: string; start_date: string; end_date: string; status: string; reason: string | null; profile?: { display_name: string } }>>([]);
  const [leaveForm, setLeaveForm] = useState({ profile_id: "", start_date: "", end_date: "", reason: "" });
  const [leaveError, setLeaveError] = useState<string | null>(null);
  const [members, setMembers] = useState<Array<{ profile_id: string; name: string; email: string | null }>>([]);
  const loadLeaves = () => fetch("/api/settings/planned-leaves").then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Planned leave gagal dimuat."); setLeaves(body.data ?? []); });
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [workloadResponse] = await Promise.all([fetch("/api/settings/workload"), loadLeaves(), fetch("/api/assignment-members").then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Anggota gagal dimuat."); setMembers(body.data ?? []); })]); const body = await workloadResponse.json(); if (!workloadResponse.ok) throw new Error(body.error ?? "Beban kerja gagal dimuat."); setRows(body.data ?? []); } catch (err) { setError(err instanceof Error ? err.message : "Data gagal dimuat."); } finally { setLoading(false); } }, []);
  const submitLeave = async () => { setLeaveError(null); const response = await fetch("/api/settings/planned-leaves", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(leaveForm) }); if (!response.ok) { const body = await response.json().catch(() => null); setLeaveError(body?.error ?? "Planned leave gagal dibuat."); return; } setLeaveForm({ profile_id: "", start_date: "", end_date: "", reason: "" }); void loadLeaves(); };
  const leaveAction = async (id: string, action: "approve" | "reject") => { const body = action === "reject" ? { reason: window.prompt("Alasan penolakan") ?? "" } : {}; await fetch(`/api/settings/planned-leaves/${id}?action=${action}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); void loadLeaves(); };
  const cancelLeave = async (leave: { id: string; status: string }) => { const reason = leave.status === "approved" ? window.prompt("Alasan pembatalan") ?? "" : ""; await fetch(`/api/settings/planned-leaves/${leave.id}`, { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reason }) }); void loadLeaves(); };
  useEffect(() => { queueMicrotask(() => { void load(); }); }, [load]);
  return (
    <main className="page-canvas">
      <div className="mb-6">
        <h1 className="text-xl font-semibold text-ink">Tim &amp; beban kerja</h1>
        <p className="mt-0.5 text-sm text-muted-foreground">Pantau pekerjaan tim dari antrean work item.</p>
      </div>
      <section className="surface-card max-w-4xl rounded-xl p-6">
        <Users className="mb-3 size-8 text-blue-600" />
        <h2 className="text-base font-semibold text-ink">Distribusi pekerjaan &amp; availability</h2>
        {loading ? <div className="mt-5 flex items-center gap-2 text-sm text-slate-500"><Loader2 className="size-4 animate-spin" />Memuat data...</div> : error ? <div className="mt-5 space-y-2"><p role="alert" className="text-sm text-red-600">{error}</p><button type="button" className="rounded-md border px-3 py-2 text-sm" onClick={() => void load()}>Coba lagi</button></div> : rows.length === 0 ? <p className="mt-3 text-sm text-muted-foreground">Belum ada pekerjaan yang ditugaskan.</p> : <div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs text-muted-foreground"><th className="pb-2">Anggota</th><th className="pb-2">Total</th><th className="pb-2">Aktif</th><th className="pb-2">Kapasitas</th><th className="pb-2">Overdue</th><th className="pb-2">Availability</th></tr></thead><tbody>{rows.map((row) => <tr key={row.profile_id} className="border-b last:border-0"><td className="py-3 font-medium text-ink">{row.profile?.display_name ?? row.profile?.email ?? row.profile_id}</td><td className="py-3">{row.total}</td><td className="py-3">{row.active}</td><td className={row.over_capacity ? "py-3 font-semibold text-red-600" : "py-3"}>{row.capacity_utilization === null ? "—" : `${row.capacity_utilization}%`}</td><td className="py-3 text-red-500">{row.overdue}</td><td className="py-3">{row.availability.is_on_leave_now ? <span className="font-medium text-amber-600">Sedang leave</span> : row.availability.next_leave_start ? <span className="text-slate-500">{row.availability.next_leave_start}–{row.availability.next_leave_end}</span> : <span className="text-emerald-600">Tersedia</span>}</td></tr>)}</tbody></table></div>}
      </section>
      <section className="surface-card mt-6 max-w-4xl rounded-xl p-6">
        <div className="flex items-center justify-between"><div><h2 className="text-base font-semibold text-ink">Planned leave</h2><p className="mt-1 text-sm text-muted-foreground">Ajukan dan proses ketersediaan anggota tim.</p></div><Plus className="size-5 text-blue-600" /></div>
        <div className="mt-4 grid gap-3 md:grid-cols-4"><Select value={leaveForm.profile_id || null} onValueChange={(value) => setLeaveForm({ ...leaveForm, profile_id: value ?? "" })}><SelectTrigger aria-label="Pilih anggota untuk planned leave" className="w-full"><SelectValue placeholder="Pilih anggota" /></SelectTrigger><SelectContent>{members.map((member) => <SelectItem key={member.profile_id} value={member.profile_id}>{member.name}{member.email ? ` · ${member.email}` : ""}</SelectItem>)}</SelectContent></Select><input aria-label="Tanggal mulai leave" className="rounded-md border px-3 py-2 text-sm" type="date" value={leaveForm.start_date} onChange={(event) => setLeaveForm({ ...leaveForm, start_date: event.target.value })} /><input aria-label="Tanggal selesai leave" className="rounded-md border px-3 py-2 text-sm" type="date" value={leaveForm.end_date} onChange={(event) => setLeaveForm({ ...leaveForm, end_date: event.target.value })} /><input aria-label="Alasan planned leave" className="rounded-md border px-3 py-2 text-sm" placeholder="Alasan (opsional)" value={leaveForm.reason} onChange={(event) => setLeaveForm({ ...leaveForm, reason: event.target.value })} /></div>
        <button type="button" className="mt-3 rounded-md bg-orange-500 px-4 py-2 text-sm font-bold text-white hover:bg-orange-600" onClick={() => void submitLeave()}>Ajukan leave</button>{leaveError && <p className="mt-2 text-sm text-red-600">{leaveError}</p>}
        <div className="mt-5 overflow-x-auto">{leaves.length === 0 ? <p className="text-sm text-muted-foreground">Belum ada planned leave.</p> : <table className="w-full text-left text-sm"><thead><tr className="border-b text-xs text-muted-foreground"><th className="pb-2">Profile</th><th className="pb-2">Periode</th><th className="pb-2">Status</th><th className="pb-2">Aksi</th></tr></thead><tbody>{leaves.map((leave) => <tr key={leave.id} className="border-b last:border-0"><td className="py-3">{leave.profile?.display_name ?? leave.profile_id}</td><td className="py-3">{leave.start_date} – {leave.end_date}</td><td className="py-3">{leave.status}</td><td className="py-3"><div className="flex gap-2">{leave.status === "pending" && <><button type="button" aria-label="Setujui planned leave" onClick={() => void leaveAction(leave.id, "approve")}><Check className="size-4 text-emerald-600" /></button><button type="button" aria-label="Tolak planned leave" onClick={() => void leaveAction(leave.id, "reject")}><X className="size-4 text-red-600" /></button></>}{["pending", "approved"].includes(leave.status) && <button type="button" aria-label="Batalkan planned leave" onClick={() => void cancelLeave(leave)}><Ban className="size-4 text-amber-600" /></button>}</div></td></tr>)}</tbody></table>}</div>
      </section>
    </main>
  );
}
