"use client";

import { useCallback, useEffect, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type Item = { id?: string; label: string; input_type: string; is_required: boolean; sort_order?: number };
type Template = { id: string; name: string; description: string | null; target_role: string; checklist_items?: Item[] };
export default function ChecklistsPage() {
  const [templates, setTemplates] = useState<Template[]>([]); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [role, setRole] = useState("maker"); const [items, setItems] = useState<Item[]>([{ label: "", input_type: "checkbox", is_required: false }]); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { const response = await fetch("/api/checklist-templates"); const body = await response.json(); if (response.ok) setTemplates(body.data ?? []); else setError(body.error ?? "Gagal memuat template."); }, []);
  useEffect(() => { queueMicrotask(() => { void load(); }); }, [load]);
  async function create() { const response = await fetch("/api/checklist-templates", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, description, target_role: role, items }) }); const body = await response.json().catch(() => null); if (!response.ok) setError(body?.error ?? "Gagal membuat template."); else { setName(""); setDescription(""); setItems([{ label: "", input_type: "checkbox", is_required: false }]); await load(); } }
  async function remove(id: string) { await fetch(`/api/checklist-templates/${id}`, { method: "DELETE" }); await load(); }
  return <div className="space-y-4"><div><h1 className="text-xl font-semibold text-slate-900">Checklist SOP</h1><p className="text-sm text-slate-500">Kelola template checklist tenant.</p></div><div className="grid gap-4 lg:grid-cols-[360px_1fr]"><Card><CardHeader><CardTitle className="text-sm">Template baru</CardTitle></CardHeader><CardContent className="space-y-3"><Input value={name} onChange={(event) => setName(event.target.value)} placeholder="Nama template" /><Input value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Deskripsi" /><Select value={role} onValueChange={(value) => setRole(value ?? "maker")}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="maker">Maker</SelectItem><SelectItem value="checker">Checker</SelectItem><SelectItem value="approver">Approver</SelectItem></SelectContent></Select>{items.map((item, index) => <div key={index} className="flex gap-2"><Input value={item.label} onChange={(event) => setItems((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, label: event.target.value } : row))} placeholder={`Item ${index + 1}`} /><Button variant="ghost" size="icon-sm" onClick={() => setItems((current) => current.filter((_, rowIndex) => rowIndex !== index))}><Trash2 className="size-4" /></Button></div>)}<Button variant="outline" onClick={() => setItems((current) => [...current, { label: "", input_type: "checkbox", is_required: false }])}><Plus className="size-4" /> Item</Button><Button className="w-full bg-orange-500 text-white hover:bg-orange-600" onClick={create} disabled={!name.trim()}>Simpan template</Button>{error && <p className="text-sm text-red-600">{error}</p>}</CardContent></Card><div className="space-y-3">{templates.map((template) => <Card key={template.id}><CardContent className="flex items-center gap-3 p-4"><div className="flex-1"><p className="font-medium text-slate-900">{template.name}</p><p className="text-sm text-slate-500">{template.description || "Tanpa deskripsi"} · {template.target_role}</p></div><Button variant="ghost" size="icon-sm" onClick={() => remove(template.id)}><Trash2 className="size-4 text-red-500" /></Button></CardContent></Card>)}{templates.length === 0 && <p className="text-sm text-slate-400">Belum ada template checklist.</p>}</div></div></div>;
}
