"use client";

import { useEffect, useRef, useState } from "react";
import { FileText, Inbox, Loader2, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ClientSelect } from "@/components/shared/client-select";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useI18n } from "@/components/i18n-provider";
import { formatDate } from "@/lib/i18n";
import { usePermissions } from "@/hooks/use-permissions";
import { AccessDenied } from "@/components/settings/settings-tabs";

type Intake = { id: string; filename: string | null; mime_type: string | null; status: string; error_message?: string | null; created_at: string; updated_at?: string };
type Draft = { id: string; intake_id: string | null; intake: Intake | null; title: string; description: string | null; type: string; client_id: string | null; maker_id: string | null; maker_name: string | null; due_at: string | null; confidence: number | null; clarification_needed: boolean; clarification_question: string | null; source_context?: string; status: string };
type Member = { profile_id: string; name: string; email: string | null; role: string };
export default function AiInboxPage() {
  const { locale, t } = useI18n();
  const { has } = usePermissions();

  if (!has("ai_review.view")) {
    return <main className="page-canvas"><AccessDenied /></main>;
  }

  const [file, setFile] = useState<File | null>(null); const [text, setText] = useState(""); const [drafts, setDrafts] = useState<Draft[]>([]); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [editing, setEditing] = useState<Draft | null>(null); const [form, setForm] = useState({ title: "", description: "", type: "ad_hoc", client_id: "", maker_id: "", due_at: "" }); const [members, setMembers] = useState<Member[]>([]); const [processingIntake, setProcessingIntake] = useState<Intake | null>(null); const pollingController = useRef<AbortController | null>(null);
  const safeSourceContext = (value: string) => value.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g, " ").trim().slice(0, 1000);
  async function load() { setLoading(true); setError(null); try { const response = await fetch("/api/ai-intake", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Draft AI gagal dimuat."); setDrafts(body.data ?? []); } catch (err) { setError(err instanceof Error ? err.message : "Draft AI gagal dimuat."); } finally { setLoading(false); } }
  useEffect(() => {
    queueMicrotask(() => { void load(); });
    window.addEventListener("workspace-language-changed", load);
    return () => window.removeEventListener("workspace-language-changed", load);
  }, []);
  async function waitForIntake(intakeId: string) { pollingController.current?.abort(); const controller = new AbortController(); pollingController.current = controller; let latest: Intake | null = null; try { for (let attempt = 0; attempt < 30; attempt += 1) { const response = await fetch(`/api/ai-intake?intake_id=${encodeURIComponent(intakeId)}`, { cache: "no-store", signal: controller.signal }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Gagal memeriksa status AI."); const intake = body.intake as Intake; latest = intake; if (intake.status === "draft" || intake.status === "failed") { setProcessingIntake(null); const intakeDrafts = (body.data ?? []).map((draft: Draft) => ({ ...draft, intake })); setDrafts((current) => [...intakeDrafts, ...current.filter((draft) => draft.intake_id !== intakeId)]); setMessage(intake.status === "failed" ? intake.error_message ?? "AI gagal memproses file." : intakeDrafts.length ? "AI selesai membuat draft." : "AI selesai membaca file, tetapi tidak menemukan action item yang eksplisit."); return; } setProcessingIntake(intake); await new Promise((resolve, reject) => { const timer = window.setTimeout(resolve, 2000); controller.signal.addEventListener("abort", () => { window.clearTimeout(timer); reject(new DOMException("Polling dibatalkan", "AbortError")); }, { once: true }); }); } setProcessingIntake(null); setMessage(latest?.status === "queued" ? "File sudah masuk antrean, tetapi worker AI belum mengambilnya. Pastikan scheduler /api/jobs/ai-extraction aktif." : "File masih diproses oleh worker AI. Coba muat ulang beberapa saat lagi."); } catch (err) { if (err instanceof DOMException && err.name === "AbortError") return; setProcessingIntake(null); throw err; } }
  async function submit() { setBusy(true); setMessage(null); const form = new FormData(); if (file) form.set("file", file); if (text.trim()) form.set("text", text); try { const response = await fetch("/api/ai-intake", { method: "POST", body: form }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Gagal memproses."); setText(""); setFile(null); await waitForIntake(body.data.intake_id); } catch (err) { setMessage(err instanceof Error ? err.message : "Gagal memproses."); } finally { setBusy(false); } }
  function openEditor(draft: Draft) { setEditing(draft); setForm({ title: draft.title, description: draft.description ?? draft.source_context ?? "", type: draft.type, client_id: draft.client_id ?? "", maker_id: draft.maker_id ?? "", due_at: draft.due_at ? draft.due_at.slice(0, 16) : "" }); }
  useEffect(() => { const controller = new AbortController(); queueMicrotask(() => { if (!form.client_id) { setMembers([]); return; } void fetch(`/api/assignment-members?client_id=${encodeURIComponent(form.client_id)}`, { signal: controller.signal, cache: "no-store" }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Anggota gagal dimuat."); setMembers(body.data ?? []); }).catch((err) => { if (err instanceof DOMException && err.name === "AbortError") return; setMessage(err instanceof Error ? err.message : "Anggota gagal dimuat."); }); }); return () => controller.abort(); }, [form.client_id]);
  useEffect(() => () => pollingController.current?.abort(), []);
  async function confirm() { if (!editing) return; setBusy(true); const response = await fetch(`/api/ai-intake/${editing.id}/confirm`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, maker_id: form.maker_id || null, due_at: form.due_at ? new Date(form.due_at).toISOString() : null }) }); const body = await response.json().catch(() => null); if (response.ok) { setEditing(null); setMessage("Task berhasil dibuat."); await load(); } else setMessage(body?.error ?? "Gagal konfirmasi."); setBusy(false); }
  const groups = Array.from(drafts.reduce((map, draft) => { const key = draft.intake_id ?? "ungrouped"; const group = map.get(key) ?? []; group.push(draft); map.set(key, group); return map; }, new Map<string, Draft[]>()).entries());
  function formatDateTime(value: string | null) { return value ? formatDate(value, locale, { dateStyle: "medium", timeStyle: "short" }) : t("common.notAvailable"); }
  const acceptedFiles = ".txt,.csv,.json,.md,.log,.pdf,.docx,.xlsx,.pptx,text/*,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.openxmlformats-officedocument.presentationml.presentation";
  return <main className="page-canvas text-slate-900"><div className="mx-auto w-full max-w-6xl space-y-6"><header><div className="flex items-center gap-2 text-xs font-semibold text-blue-600"><Sparkles className="size-4" /> Assisted Operations</div><h1 className="mt-3 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">Inbox AI</h1><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500">Upload dokumen atau tempel instruksi. AI hanya membuat draft; keputusan dan konfirmasi tetap dilakukan manusia.</p></header>
    {has("ai_review.use") ? (
      <Card className="surface-card rounded-2xl shadow-none">
        <CardHeader className="border-b border-slate-100">
          <CardTitle className="flex items-center gap-2 text-lg font-bold text-slate-950">
            <FileText className="size-5 text-blue-600" /> Input dokumen atau instruksi
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 p-5 sm:p-6">
          <Label htmlFor="ai-file">File sumber</Label>
          <input id="ai-file" type="file" accept={acceptedFiles} onChange={(event) => setFile(event.target.files?.[0] ?? null)} className="block w-full rounded-lg border border-slate-200 bg-white p-2.5 text-sm" />
          <Label htmlFor="ai-text">Teks sumber</Label>
          <textarea id="ai-text" aria-label="Teks sumber untuk AI" value={text} onChange={(event) => setText(event.currentTarget.value)} placeholder="Tempel isi dokumen atau instruksi pekerjaan..." rows={6} className="w-full rounded-lg border border-slate-200 p-3 text-sm shadow-sm outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100" />
          <div className="flex flex-wrap items-center gap-3">
            <Button onClick={submit} disabled={busy || (!file && !text.trim())} className="cta-primary">
              {busy ? <><Loader2 className="size-4 animate-spin" />Memproses...</> : <><Sparkles className="size-4" />Baca dengan AI</>}
            </Button>
            {processingIntake && <span className="rounded-full bg-amber-50 px-3 py-1.5 text-xs font-semibold text-amber-700">{processingIntake.status === "queued" ? "Menunggu antrean" : "Sedang dianalisis"}</span>}
          </div>
          {message && <p role="status" className="text-sm text-slate-600">{message}</p>}
        </CardContent>
      </Card>
    ) : (
      <Card className="surface-card rounded-2xl shadow-none p-8 text-center flex flex-col items-center justify-center">
        <Inbox className="size-12 text-blue-100 mb-4" />
        <h2 className="text-lg font-bold text-slate-900">Akses terbatas</h2>
        <p className="mt-2 text-sm text-slate-500">Anda hanya memiliki akses untuk melihat draft AI.</p>
      </Card>
    )}
    <section className="space-y-4"><div className="flex items-end justify-between gap-3"><div><h2 className="text-lg font-bold text-slate-950">Draft AI</h2><p className="mt-1 text-sm text-slate-500">Tinjau hasil AI sebelum menjadi task operasional.</p></div><div className="hidden rounded-lg bg-blue-50 p-2 text-blue-600 sm:block"><Inbox className="size-5" /></div></div>{loading ? <div className="surface-card rounded-2xl p-6 text-sm text-slate-500" role="status"><Loader2 className="mr-2 inline size-4 animate-spin" />Memuat draft...</div> : error ? <div className="space-y-2 rounded-xl border border-red-200 bg-red-50 p-4"><p role="alert" className="text-sm text-red-700">{error}</p><Button variant="outline" onClick={() => void load()}>Coba lagi</Button></div> : drafts.length === 0 ? <div className="surface-card rounded-2xl p-10 text-center"><Inbox className="mx-auto size-10 text-slate-300" /><p className="mt-3 text-sm text-slate-500">Belum ada draft.</p><p className="mt-1 text-xs text-slate-400">Draft baru akan tampil setelah dokumen selesai dianalisis.</p></div> : groups.map(([groupId, group]) => { const intake = group[0]?.intake; return <Card key={groupId} className="surface-card rounded-2xl shadow-none"><CardHeader className="space-y-3"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><CardTitle className="text-base font-bold text-slate-950">{intake?.filename ?? "Input teks langsung"}</CardTitle><p className="mt-1 text-xs text-slate-500">Batch ID: {intake?.id ?? "—"}</p></div><span className="w-fit rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-700">{intake?.status ?? "Tanpa intake"}</span></div><div className="grid gap-2 text-xs text-slate-500 sm:grid-cols-3"><span>Upload: {formatDateTime(intake?.created_at ?? null)}</span><span>Jumlah draft: {group.length}</span><span>Status draft: {group.every((draft) => draft.status !== "draft") ? "Selesai" : "Perlu Ditinjau"}</span></div></CardHeader><CardContent className="space-y-3">{group.map((draft) => <div key={draft.id} className="flex flex-col gap-3 rounded-xl border border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-slate-900">{draft.title}</p><p className="mt-1 text-sm text-slate-500">{draft.type} · Klien: {draft.client_id ? "Sudah dipilih" : "Belum dipilih"} · PIC: {draft.maker_name ?? "Belum ditentukan"}</p>{draft.clarification_needed && <p className="mt-2 text-sm text-amber-700">{draft.clarification_question}</p>}</div>{draft.status === "draft" && has("ai_review.decide") && (
  <Button onClick={() => openEditor(draft)} className="shrink-0">
    Edit & Konfirmasi
  </Button>
)}</div>)}</CardContent></Card>; })}</section><Dialog open={Boolean(editing)} onOpenChange={(open) => !open && setEditing(null)}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Edit draft sebelum membuat task</DialogTitle><DialogDescription>Periksa hasil AI. Pilih Klien dan PIC dari daftar yang tersedia.</DialogDescription></DialogHeader><div className="grid gap-4 py-2"><label className="space-y-1.5"><Label htmlFor="ai-title">Judul</Label><Input id="ai-title" value={form.title} onChange={(event) => setForm({ ...form, title: event.currentTarget.value })} /></label><label className="space-y-1.5"><Label htmlFor="ai-description">Deskripsi</Label><textarea id="ai-description" value={form.description} onChange={(event) => setForm({ ...form, description: event.currentTarget.value })} rows={4} className="w-full rounded-lg border border-slate-200 p-3 text-sm" /></label><div className="grid gap-4 sm:grid-cols-2"><ClientSelect id="ai-draft-client" value={form.client_id} onChange={(value) => setForm({ ...form, client_id: value, maker_id: "" })} /><label className="space-y-1.5"><Label>Jenis pekerjaan</Label><Select value={form.type} onValueChange={(value) => setForm({ ...form, type: value ?? "ad_hoc" })}><SelectTrigger aria-label="Jenis pekerjaan"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="routine">Routine</SelectItem><SelectItem value="project">Project</SelectItem><SelectItem value="ad_hoc">Ad Hoc</SelectItem><SelectItem value="report">Report</SelectItem></SelectContent></Select></label></div><label className="space-y-1.5"><Label>PIC / Maker</Label><Select value={form.maker_id || null} onValueChange={(value) => setForm({ ...form, maker_id: value ?? "" })}><SelectTrigger aria-label="PIC atau maker"><SelectValue placeholder={form.client_id ? "Pilih PIC" : "Pilih klien dulu"} /></SelectTrigger><SelectContent>{members.map((member) => <SelectItem key={member.profile_id} value={member.profile_id}>{member.name}{member.email ? ` · ${member.email}` : ""}</SelectItem>)}</SelectContent></Select></label><label className="space-y-1.5"><Label htmlFor="ai-due">Tenggat</Label><Input id="ai-due" type="datetime-local" value={form.due_at} onChange={(event) => setForm({ ...form, due_at: event.currentTarget.value })} /></label>{editing?.source_context && <div className="rounded-lg bg-slate-50 p-3 text-xs text-slate-600">Konteks AI: {safeSourceContext(editing.source_context)}</div>}</div><DialogFooter><Button variant="outline" onClick={() => setEditing(null)}>Batal</Button><Button onClick={confirm} disabled={busy || !form.title.trim() || !form.client_id}>{busy ? "Membuat..." : "Konfirmasi & Buat Task"}</Button></DialogFooter></DialogContent></Dialog></div></main>;
}
