ALTER TABLE acct_ctrl.meetings ADD COLUMN IF NOT EXISTS attendance TEXT NOT NULL DEFAULT '';
ALTER TABLE acct_ctrl.meetings ADD COLUMN IF NOT EXISTS discussion TEXT NOT NULL DEFAULT '';
ALTER TABLE acct_ctrl.meetings ADD COLUMN IF NOT EXISTS action_items TEXT NOT NULL DEFAULT '';
ALTER TABLE acct_ctrl.meetings ADD COLUMN IF NOT EXISTS blockers TEXT NOT NULL DEFAULT '';
ALTER TABLE acct_ctrl.meetings ADD COLUMN IF NOT EXISTS next_steps TEXT NOT NULL DEFAULT '';
ALTER TABLE acct_ctrl.meetings ADD COLUMN IF NOT EXISTS parsed_at TIMESTAMPTZ;
