CREATE TABLE acct_ctrl.approval_authorities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES acct_ctrl.organizations(id), client_id UUID REFERENCES acct_ctrl.clients(id), entity_id UUID REFERENCES acct_ctrl.entities(id), profile_id UUID NOT NULL REFERENCES acct_ctrl.profiles(id), role TEXT NOT NULL, max_amount NUMERIC(20,2) NOT NULL, currency_code CHAR(3) NOT NULL DEFAULT 'IDR', max_risk_level TEXT NOT NULL DEFAULT 'low', approval_level INTEGER NOT NULL DEFAULT 0, effective_from TIMESTAMPTZ NOT NULL, effective_until TIMESTAMPTZ, is_active BOOLEAN NOT NULL DEFAULT true, created_by UUID NOT NULL REFERENCES acct_ctrl.profiles(id), reason TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT authority_amount_nonnegative CHECK (max_amount >= 0), CONSTRAINT authority_period CHECK (effective_until IS NULL OR effective_until > effective_from), CONSTRAINT authority_currency CHECK (currency_code ~ '^[A-Z]{3}$'), CONSTRAINT authority_level CHECK (approval_level >= 0)
);
CREATE INDEX idx_approval_authorities_scope ON acct_ctrl.approval_authorities(organization_id, profile_id, client_id, entity_id, role, effective_from, effective_until) WHERE is_active;

CREATE TABLE acct_ctrl.delegations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES acct_ctrl.organizations(id), client_id UUID REFERENCES acct_ctrl.clients(id), entity_id UUID REFERENCES acct_ctrl.entities(id), principal_id UUID NOT NULL REFERENCES acct_ctrl.profiles(id), delegate_id UUID NOT NULL REFERENCES acct_ctrl.profiles(id), role TEXT NOT NULL, max_amount NUMERIC(20,2) NOT NULL, currency_code CHAR(3) NOT NULL DEFAULT 'IDR', max_risk_level TEXT NOT NULL DEFAULT 'low', approval_level INTEGER NOT NULL DEFAULT 0, effective_from TIMESTAMPTZ NOT NULL, effective_until TIMESTAMPTZ NOT NULL, status TEXT NOT NULL DEFAULT 'active', approved_by UUID REFERENCES acct_ctrl.profiles(id), reason TEXT NOT NULL, revoked_at TIMESTAMPTZ, revoked_by UUID REFERENCES acct_ctrl.profiles(id), revocation_reason TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), CONSTRAINT delegation_not_self CHECK (principal_id <> delegate_id), CONSTRAINT delegation_period CHECK (effective_until > effective_from), CONSTRAINT delegation_amount_nonnegative CHECK (max_amount >= 0), CONSTRAINT delegation_status CHECK (status IN ('active','revoked','expired'))
);
CREATE INDEX idx_delegations_active_scope ON acct_ctrl.delegations(organization_id, delegate_id, client_id, entity_id, role, effective_from, effective_until) WHERE status = 'active';

ALTER TABLE acct_ctrl.approval_authorities ENABLE ROW LEVEL SECURITY;
ALTER TABLE acct_ctrl.delegations ENABLE ROW LEVEL SECURITY;
CREATE POLICY approval_authorities_org_access ON acct_ctrl.approval_authorities FOR ALL TO authenticated USING (organization_id = acct_ctrl.current_organization_id()) WITH CHECK (organization_id = acct_ctrl.current_organization_id());
CREATE POLICY delegations_org_access ON acct_ctrl.delegations FOR ALL TO authenticated USING (organization_id = acct_ctrl.current_organization_id()) WITH CHECK (organization_id = acct_ctrl.current_organization_id());
