"use client";

import { useCallback, useEffect, useState } from "react";
import { Link2, Loader2, Search, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";

type Dependency = { id: string; depends_on_id: string; dependency_type: string; depends_on?: { title: string; status: string } };
type Candidate = { id: string; title: string; status: string; due_at: string | null };
export function DependencyPanel({ workItemId }: { workItemId: string }) {
  const [items, setItems] = useState<Dependency[]>([]); const [dependencyId, setDependencyId] = useState(""); const [query, setQuery] = useState(""); const [candidates, setCandidates] = useState<Candidate[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { const response = await fetch(`/api/work-items/${workItemId}/dependencies`); const body = await response.json(); if (response.ok) setItems(body.data ?? []); else setError(body.error ?? "Gagal memuat dependency."); }, [workItemId]);
  useEffect(() => { queueMicrotask(() => { void load(); }); }, [load]);
  useEffect(() => { if (!query.trim()) return; const controller = new AbortController(); const timer = setTimeout(() => { fetch(`/api/work-items?search=${encodeURIComponent(query)}&limit=10&detail=0&count=0`, { signal: controller.signal }).then(async (response) => { const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error ?? "Gagal mencari work item."); return body; }).then((body) => setCandidates((body?.data ?? []).filter((item: Candidate) => item.id !== workItemId && !items.some((dependency) => dependency.depends_on_id === item.id)))).catch((reason) => { if (reason instanceof DOMException && reason.name === "AbortError") return; setError(reason instanceof Error ? reason.message : "Gagal mencari work item."); }); }, 250); return () => { clearTimeout(timer); controller.abort(); }; }, [query, workItemId, items]);
  async function add() { setBusy(true); setError(null); const response = await fetch(`/api/work-items/${workItemId}/dependencies`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ depends_on_id: dependencyId }) }); const body = await response.json().catch(() => null); if (!response.ok) setError(body?.error ?? "Gagal menambah dependency."); else { setDependencyId(""); setQuery(""); await load(); } setBusy(false); }
  async function remove(id: string) { setBusy(true); await fetch(`/api/work-items/${workItemId}/dependencies`, { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ dependency_id: id }) }); await load(); setBusy(false); }
  return <div className="space-y-3"><div className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-2.5 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><Input value={query} onChange={(event) => { setQuery(event.target.value); if (!event.target.value.trim()) setCandidates([]); }} placeholder="Cari prerequisite berdasarkan judul" className="pl-8" /></div><Button onClick={add} disabled={busy || !dependencyId}><Link2 className="size-4" /> Tambah</Button></div>{candidates.length > 0 && <div className="space-y-1 rounded-lg border border-slate-100 p-2">{candidates.map((candidate) => <button type="button" key={candidate.id} className="block w-full rounded-md px-2 py-1.5 text-left text-sm hover:bg-slate-50" onClick={() => { setDependencyId(candidate.id); setQuery(candidate.title); setCandidates([]); }}>{candidate.title}<span className="ml-2 text-xs text-slate-400">{candidate.status}</span></button>)}</div>}{items.length === 0 ? <p className="text-sm text-slate-400">Belum ada dependency.</p> : items.map((item) => <div key={item.id} className="flex items-center gap-2 rounded-lg border border-slate-100 p-3"><div className="flex-1"><p className="text-sm font-medium">{item.depends_on?.title ?? item.depends_on_id}</p><p className="text-xs text-slate-500">{item.dependency_type} · {item.depends_on?.status ?? ""}</p></div><Tooltip><TooltipTrigger render={<Button variant="ghost" size="icon-sm" disabled={busy} onClick={() => remove(item.id)} aria-label="Hapus dependency" />}>{busy ? <Loader2 className="size-4 animate-spin" /> : <X className="size-4 text-red-500" />}</TooltipTrigger><TooltipContent>Hapus dependency</TooltipContent></Tooltip></div>)}{error && <p className="text-sm text-red-600">{error}</p>}</div>;
}
